### ISSUE TITLE
Weird results when running with text from Gutenberg corpus

### ISSUE THREAD

**Issue by cgratie** [csurfer/rake-nltk#2]
I have tried this simple snippet to test keyword extraction on longer text using NLTK.
```
from nltk.corpus import gutenberg
from rake_nltk.rake import Rake
r = Rake()
r.extract_keywords_from_text(gutenberg.raw("austen-emma.txt"))
for phrase in r.get_ranked_phrases()[:5]:
    print phrase
```
The output I got is as follows:
```
.-- _she_ _felt_ _the_ _engagement_ _to_ _be_ _a_ _source_ _of_ _repentance_ _and_ _misery_ _to_ _each_
best time -- never tired -- every sort good -- hautboy infinitely superior --
said nothing worth hearing -- looked without seeing -- admired without intelligence -- listened without knowing
scarce -- chili preferred -- white wood finest flavour
without scruple -- without apology -- without much apparent diffidence
```
I assume this is caused by either the word tokenizer or the sentence tokenizer, but I'm not sure how to fix it.

**Comment by csurfer** [comment]
This behaviour is because the

`nltk.tokenize.wordpunkt_tokenize()`

doesn't split punctuation clusters. i,e 

`nltk.tokenize.wordpunct_tokenize('--') => ['--']` and 
`nltk.tokenize.wordpunct_tokenize(';.') => [';.']`

It didn't seem like a good idea for the class to have cleaning and keyword extraction logic. So kept the cleaning logic out. Try cleaning the text before using the Keyword extraction.

**Comment by cgratie** [comment]
Indeed, removing such punctuation clusters from the text does remove non-words from the output Another option is to pass the punctuation clusters to `Rake` via the `punctuation` argument.
